#!/bin/sh

DATA=`date`
SYSTEM=`hostname`
SYSADMIN="root"

if [ -f /var/lib/aide/aide.db ];
then
 nice -20 /usr/bin/aide --check >/var/lib/aide/$$
 LIN=`grep -c . /var/lib/aide/$DATA2`
 if [ "$LIN" -gt "1" ]; then
     mail -s "!!! $SYSTEM $DATA AIDE !!!" $SYSADMIN </var/lib/aide/$$
 fi
 rm -f /var/lib/aide/$$
else
 mail -s "AIDE" $SYSADMIN "You don't have got /var/lib/aide/aide.db, do 'aide --init'"
fi
