#!/bin/sh

# Get service config
[ -f /etc/sysconfig/aide ] && . /etc/sysconfig/aide

DATA=`date`
SYSTEM=`hostname`
SYSADMIN="root"

if [ -f /var/lib/aide/aide.db ];
then
 nice -20 /usr/bin/aide --$AIDE_WORK_MODE >/var/lib/aide/$$
 LIN=`grep -c . /var/lib/aide/$$`
 if [ "$LIN" -gt "1" ]; then
     mail -s "AIDE $SYSTEM $DATA" $SYSADMIN </var/lib/aide/$$
 fi
 rm -f /var/lib/aide/$$
else
 mail -s "AIDE" $SYSADMIN "You don't have got /var/lib/aide/aide.db, do 'aide --init'"
fi
